-- Insertar fabricantes sin especificar IDs
INSERT INTO fabricante (nombre) VALUES ('Asus');
INSERT INTO fabricante (nombre) VALUES ('Samsung');
INSERT INTO fabricante (nombre) VALUES ('Apple');
INSERT INTO fabricante (nombre) VALUES ('Lenovo');
INSERT INTO fabricante (nombre) VALUES ('HP');
INSERT INTO fabricante (nombre) VALUES ('Dell');
INSERT INTO fabricante (nombre) VALUES ('Acer');
INSERT INTO fabricante (nombre) VALUES ('Sony');
INSERT INTO fabricante (nombre) VALUES ('Microsoft');
INSERT INTO fabricante (nombre) VALUES ('LG');

-- Insertar productos sin especificar IDs
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Disco duro SATA3 1TB', 86.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Memoria RAM DDR4 8GB', 45.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Tarjeta gráfica GTX 1660', 249.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Placa base ATX Z390', 129.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor LED 24"', 159.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado mecánico', 89.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse óptico', 25.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Caja de PC ATX', 59.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Fuente de alimentación 650W', 79.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Ventilador RGB', 19.99, 1);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('SSD M.2 500GB', 89.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Smartphone Galaxy S21', 799.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Tablet Galaxy Tab S7', 649.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Smartwatch Galaxy Watch 3', 399.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor UltraWide 34"', 499.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Televisor QLED 55"', 999.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares Galaxy Buds', 129.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Disco duro externo 2TB', 109.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Cámara de seguridad', 199.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Barra de sonido', 299.99, 2);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('iPhone 13', 999.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('MacBook Pro 13"', 1299.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('iPad Pro 11"', 799.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Apple Watch Series 6', 399.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('AirPods Pro', 249.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('HomePod mini', 99.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Magic Keyboard', 129.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse Magic', 79.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Cargador MagSafe', 39.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Apple TV 4K', 179.99, 3);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop ThinkPad X1', 1399.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor ThinkVision', 229.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Tablet Yoga', 349.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Smartphone Motorola G9', 199.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('SSD ThinkPad 1TB', 139.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado mecánico Lenovo', 99.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse Lenovo', 29.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Estación de acoplamiento', 199.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor portátil', 189.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares Lenovo', 79.99, 4);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Pavilion 15"', 749.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor HP 27"', 229.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Impresora HP LaserJet', 199.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado HP', 49.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse HP', 29.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('All-in-One HP 24"', 599.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Disco duro externo HP', 89.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Memoria RAM HP 16GB', 129.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor curvo HP', 299.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares HP', 59.99, 5);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop XPS 13', 999.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor Dell 27"', 319.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado mecánico Dell', 129.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse inalámbrico Dell', 59.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Docking Station Dell', 199.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Alienware', 1499.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares gaming Dell', 149.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado RGB Dell', 179.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor ultrafino Dell', 379.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Memoria RAM Dell 8GB', 79.99, 6);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Acer Aspire 5', 649.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor Acer 24"', 159.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado gaming Acer', 99.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse gaming Acer', 49.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares gaming Acer', 79.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Predator', 1299.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor curvo Acer', 349.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('SSD Acer 512GB', 119.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop TravelMate', 799.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Proyector Acer', 499.99, 7);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Cámara Sony A7 III', 1999.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Televisor OLED 65"', 2999.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares Sony WH-1000XM4', 349.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Smartphone Xperia 1 II', 1199.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Consola PlayStation 5', 499.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Control DualSense', 69.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Altavoz Sony SRS-XB43', 199.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Proyector Sony 4K', 2499.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('SSD externo Sony', 169.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Barra de sonido Sony', 399.99, 8);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Surface Pro 7', 899.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Tablet Surface Go', 399.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor Surface Studio', 3499.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Teclado Surface', 129.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Mouse Surface', 79.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares Surface', 249.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Dock Surface', 199.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Laptop Surface Book 3', 1599.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Pen Surface', 99.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Hub USB Surface', 89.99, 9);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Televisor LG OLED 55"', 1299.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Lavadora LG 9kg', 699.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Refrigerador LG', 1199.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Aire acondicionado LG', 599.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Microondas LG', 199.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Auriculares LG', 149.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Barra de sonido LG', 299.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Monitor LG 27"', 249.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Smartphone LG V60', 799.99, 10);
INSERT INTO producto (nombre, precio, id_fabricante) VALUES ('Proyector LG', 999.99, 10);
